dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"
dotenv: .env
networks:
  rinkeby:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
